# flake8: noqa

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from aifs_client.api_client import ApiClient

# import Configuration
from aifs_client.configuration import Configuration

# import exceptions
from aifs_client.exceptions import OpenApiException
from aifs_client.exceptions import ApiAttributeError
from aifs_client.exceptions import ApiTypeError
from aifs_client.exceptions import ApiValueError
from aifs_client.exceptions import ApiKeyError
from aifs_client.exceptions import ApiException
