# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.filter_annotations_in_data_view_request import FilterAnnotationsInDataViewRequest
from openapi_client import configuration


class TestFilterAnnotationsInDataViewRequest(unittest.TestCase):
    """FilterAnnotationsInDataViewRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
