# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.time_fmt_in_ms import TimeFmtInMs
from openapi_client import configuration


class TestTimeFmtInMs(unittest.TestCase):
    """TimeFmtInMs unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
