# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.annotation_template_type_list import AnnotationTemplateTypeList
from openapi_client import configuration


class TestAnnotationTemplateTypeList(unittest.TestCase):
    """AnnotationTemplateTypeList unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
