# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class AnnotationViewData(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            dataViewId = schemas.UUIDSchema
            annotationTemplateId = schemas.UUIDSchema
        
            @staticmethod
            def viewType() -> typing.Type['DataViewType']:
                return DataViewType
        
            @staticmethod
            def dataItems() -> typing.Type['AnnotationData']:
                return AnnotationData
            __annotations__ = {
                "dataViewId": dataViewId,
                "annotationTemplateId": annotationTemplateId,
                "viewType": viewType,
                "dataItems": dataItems,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dataViewId"]) -> MetaOapg.properties.dataViewId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["annotationTemplateId"]) -> MetaOapg.properties.annotationTemplateId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["viewType"]) -> 'DataViewType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dataItems"]) -> 'AnnotationData': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["dataViewId", "annotationTemplateId", "viewType", "dataItems", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dataViewId"]) -> typing.Union[MetaOapg.properties.dataViewId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["annotationTemplateId"]) -> typing.Union[MetaOapg.properties.annotationTemplateId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["viewType"]) -> typing.Union['DataViewType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dataItems"]) -> typing.Union['AnnotationData', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["dataViewId", "annotationTemplateId", "viewType", "dataItems", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        dataViewId: typing.Union[MetaOapg.properties.dataViewId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        annotationTemplateId: typing.Union[MetaOapg.properties.annotationTemplateId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        viewType: typing.Union['DataViewType', schemas.Unset] = schemas.unset,
        dataItems: typing.Union['AnnotationData', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AnnotationViewData':
        return super().__new__(
            cls,
            *_args,
            dataViewId=dataViewId,
            annotationTemplateId=annotationTemplateId,
            viewType=viewType,
            dataItems=dataItems,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.annotation_data import AnnotationData
from openapi_client.model.data_view_type import DataViewType
