# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class DataViewType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "raw-data": "RAWDATA",
            "annotation": "ANNOTATION",
            "model": "MODEL",
            "dataset-zip": "DATASETZIP",
            "artifact": "ARTIFACT",
        }
    
    @schemas.classproperty
    def RAWDATA(cls):
        return cls("raw-data")
    
    @schemas.classproperty
    def ANNOTATION(cls):
        return cls("annotation")
    
    @schemas.classproperty
    def MODEL(cls):
        return cls("model")
    
    @schemas.classproperty
    def DATASETZIP(cls):
        return cls("dataset-zip")
    
    @schemas.classproperty
    def ARTIFACT(cls):
        return cls("artifact")
