# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ZipFormat(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    the structure of the files in zip file
    """


    class MetaOapg:
        enum_value_to_name = {
            "image-classification": "IMAGECLASSIFICATION",
            "rgbd-bounding-box-2d-and-3d": "RGBDBOUNDINGBOX2DAND3D",
            "image-segmentation-masks": "IMAGESEGMENTATIONMASKS",
            "ocr": "OCR",
            "coco": "COCO",
            "raw-data-images": "RAWDATAIMAGES",
            "sam": "SAM",
            "points-3d-zip": "POINTS3DZIP",
        }
    
    @schemas.classproperty
    def IMAGECLASSIFICATION(cls):
        return cls("image-classification")
    
    @schemas.classproperty
    def RGBDBOUNDINGBOX2DAND3D(cls):
        return cls("rgbd-bounding-box-2d-and-3d")
    
    @schemas.classproperty
    def IMAGESEGMENTATIONMASKS(cls):
        return cls("image-segmentation-masks")
    
    @schemas.classproperty
    def OCR(cls):
        return cls("ocr")
    
    @schemas.classproperty
    def COCO(cls):
        return cls("coco")
    
    @schemas.classproperty
    def RAWDATAIMAGES(cls):
        return cls("raw-data-images")
    
    @schemas.classproperty
    def SAM(cls):
        return cls("sam")
    
    @schemas.classproperty
    def POINTS3DZIP(cls):
        return cls("points-3d-zip")
