# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aifs_client import schemas  # noqa: F401


class CreateDataViewRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            dataViewName = schemas.StrSchema
            description = schemas.StrSchema
        
            @staticmethod
            def viewType() -> typing.Type['DataViewType']:
                return DataViewType
        
            @staticmethod
            def rawDataType() -> typing.Type['RawDataType']:
                return RawDataType
        
            @staticmethod
            def zipFormat() -> typing.Type['ZipFormat']:
                return ZipFormat
            relatedDataViewId = schemas.UUIDSchema
            annotationTemplateId = schemas.UUIDSchema
            rawDataViewId = schemas.UUIDSchema
            annotationViewId = schemas.UUIDSchema
            __annotations__ = {
                "dataViewName": dataViewName,
                "description": description,
                "viewType": viewType,
                "rawDataType": rawDataType,
                "zipFormat": zipFormat,
                "relatedDataViewId": relatedDataViewId,
                "annotationTemplateId": annotationTemplateId,
                "rawDataViewId": rawDataViewId,
                "annotationViewId": annotationViewId,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dataViewName"]) -> MetaOapg.properties.dataViewName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["viewType"]) -> 'DataViewType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rawDataType"]) -> 'RawDataType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["zipFormat"]) -> 'ZipFormat': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["relatedDataViewId"]) -> MetaOapg.properties.relatedDataViewId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["annotationTemplateId"]) -> MetaOapg.properties.annotationTemplateId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rawDataViewId"]) -> MetaOapg.properties.rawDataViewId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["annotationViewId"]) -> MetaOapg.properties.annotationViewId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["dataViewName", "description", "viewType", "rawDataType", "zipFormat", "relatedDataViewId", "annotationTemplateId", "rawDataViewId", "annotationViewId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dataViewName"]) -> typing.Union[MetaOapg.properties.dataViewName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["viewType"]) -> typing.Union['DataViewType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rawDataType"]) -> typing.Union['RawDataType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["zipFormat"]) -> typing.Union['ZipFormat', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["relatedDataViewId"]) -> typing.Union[MetaOapg.properties.relatedDataViewId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["annotationTemplateId"]) -> typing.Union[MetaOapg.properties.annotationTemplateId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rawDataViewId"]) -> typing.Union[MetaOapg.properties.rawDataViewId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["annotationViewId"]) -> typing.Union[MetaOapg.properties.annotationViewId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["dataViewName", "description", "viewType", "rawDataType", "zipFormat", "relatedDataViewId", "annotationTemplateId", "rawDataViewId", "annotationViewId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        dataViewName: typing.Union[MetaOapg.properties.dataViewName, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        viewType: typing.Union['DataViewType', schemas.Unset] = schemas.unset,
        rawDataType: typing.Union['RawDataType', schemas.Unset] = schemas.unset,
        zipFormat: typing.Union['ZipFormat', schemas.Unset] = schemas.unset,
        relatedDataViewId: typing.Union[MetaOapg.properties.relatedDataViewId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        annotationTemplateId: typing.Union[MetaOapg.properties.annotationTemplateId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        rawDataViewId: typing.Union[MetaOapg.properties.rawDataViewId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        annotationViewId: typing.Union[MetaOapg.properties.annotationViewId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreateDataViewRequest':
        return super().__new__(
            cls,
            *_args,
            dataViewName=dataViewName,
            description=description,
            viewType=viewType,
            rawDataType=rawDataType,
            zipFormat=zipFormat,
            relatedDataViewId=relatedDataViewId,
            annotationTemplateId=annotationTemplateId,
            rawDataViewId=rawDataViewId,
            annotationViewId=annotationViewId,
            _configuration=_configuration,
            **kwargs,
        )

from aifs_client.model.data_view_type import DataViewType
from aifs_client.model.raw_data_type import RawDataType
from aifs_client.model.zip_format import ZipFormat
