# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aifs_client import schemas  # noqa: F401


class UploadAnnotationFormat(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    the format of the data
    """
    
    @schemas.classproperty
    def ALLANNOTATIONSINGLEFILELOCAL(cls):
        return cls("all-annotation-single-file-local")
    
    @schemas.classproperty
    def PERANNOTATIONPERFILELOCAL(cls):
        return cls("per-annotation-per-file-local")
