# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.annotation_templates_annotation_template_id_copy.post import CopyAnnotationTemplate
from openapi_client.paths.annotation_templates.post import CreateAnnotationTemplate
from openapi_client.paths.annotation_templates_annotation_template_id.delete import DeleteAnnotationTemplate
from openapi_client.paths.annotation_templates_annotation_template_id_details.get import GetAnnoTemplateDetails
from openapi_client.paths.annotation_templates.get import GetAnnoTemplateList
from openapi_client.paths.annotation_templates.put import UpdateAnnotationTemplate


class AnnotationTemplateApi(
    CopyAnnotationTemplate,
    CreateAnnotationTemplate,
    DeleteAnnotationTemplate,
    GetAnnoTemplateDetails,
    GetAnnoTemplateList,
    UpdateAnnotationTemplate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
