# coding: utf-8

"""
    Aifs api

    aifs api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from aifs_client.paths.data_views_data_view_id_annotations.post import UploadAnnotationToDataView
from aifs_client.paths.data_views_data_view_id_dataset_zip.post import UploadDatasetZipToDataView
from aifs_client.paths.data_views_data_view_id_artifact.post import UploadFileToDataView
from aifs_client.paths.data_views_data_view_id_model.post import UploadModelDataToDataView
from aifs_client.paths.data_views_data_view_id_raw_data.post import UploadRawDataToDataView


class DataViewUploadApi(
    UploadAnnotationToDataView,
    UploadDatasetZipToDataView,
    UploadFileToDataView,
    UploadModelDataToDataView,
    UploadRawDataToDataView,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
